#ifndef SSD_1306_ENUM_H
#define SSD_1306_ENUM_H

enum COMMANDS {
  SET_CONTRAST_CONTROL = 0x81,
  SET_CONTRAST_127 = 0x7F,
  SET_CONTRAST_143 = 0x8F,
  SET_CONTRAST_207 = 0xCF,
  SET_DISPLAY_BY_RAM = 0xA4,
  SET_ENTIRE_DISPLAY_ON = 0xA5,
  SET_NORMAL_DISPLAY = 0xA6,
  SET_INVERSE_DISPLAY = 0xA7,
  SET_DISPLAY_OFF = 0xAE,
  SET_DISPLAY_ON = 0xAF,

  SET_DEACTIVATE_SCROLL = 0x2E,

  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_0 = 0x00,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_1 = 0x01,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_2 = 0x02,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_3 = 0x03,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_4 = 0x04,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_5 = 0x05,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_6 = 0x06,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_7 = 0x07,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_8 = 0x08,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_9 = 0x09,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_10 = 0x0A,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_11 = 0x0B,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_12 = 0x0C,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_13 = 0x0D,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_14 = 0x0E,
  SET_LOWER_COLUMN_START_ADDR_FOR_PAGE_15 = 0x0F,

  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_0 = 0x10,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_1 = 0x11,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_2 = 0x12,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_3 = 0x13,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_4 = 0x14,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_5 = 0x15,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_6 = 0x16,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_7 = 0x17,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_8 = 0x18,
  SET_HIGHER_COLUMN_START_ADDR_FOR_PAGE_9 = 0x19,
  SET_HIGHER_COLUMN_START_ADDR_10_FOR_PAGE = 0x1A,
  SET_HIGHER_COLUMN_START_ADDR_11_FOR_PAGE = 0x1B,
  SET_HIGHER_COLUMN_START_ADDR_12_FOR_PAGE = 0x1C,
  SET_HIGHER_COLUMN_START_ADDR_13_FOR_PAGE = 0x1D,
  SET_HIGHER_COLUMN_START_ADDR_14_FOR_PAGE = 0x1E,
  SET_HIGHER_COLUMN_START_ADDR_15_FOR_PAGE = 0x1F,

  SET_PAGE_START_ADDR_0 = 0xB0,
  SET_PAGE_START_ADDR_1 = 0xB1,
  SET_PAGE_START_ADDR_2 = 0xB2,
  SET_PAGE_START_ADDR_3 = 0xB3,
  SET_PAGE_START_ADDR_4 = 0xB4,
  SET_PAGE_START_ADDR_5 = 0xB5,
  SET_PAGE_START_ADDR_6 = 0xB6,
  SET_PAGE_START_ADDR_7 = 0xB7,

  SET_COLUMN_ADDR = 0x21,
  SET_PAGE_ADDR_CONTROL = 0x22,

  SET_HORIZONTAL_MEMORY_ADDRESSING_MODE = 0x00,
  SET_VERTICAL_MEMORY_ADDRESSING_MODE = 0x01,
  SET_PAGE_MEMORY_ADDRESSING_MODE = 0x02,

  SET_START_LINE = 0x40,

  SET_COM_SCAN_INCREMENT = 0xC0,
  SET_COM_SCAN_DECREMENT = 0xC8,

  SET_SEG_REMAP_OFF = 0xA0,
  SET_SEG_REMAP_ON = 0xA1,

  SET_MEMORY_ADDRESSING_MODE_CONTROL = 0x20,

  SET_DISPLAY_CLK_DIVIDER_CONTROL = 0xD5,
  SET_DISPLAY_CLK_DIVIDER_128 = 0x80,
  SET_MULTIPLEX_RATIO_CONTROL = 0xA8,
  SET_MULTIPLEX_RATIO_32 = 0x1F,
  SET_MULTIPLEX_RATIO_64 = 0x3F,
  SET_DISPLAY_OFFSET_CONTROL = 0xD3,
  SET_DISPLAY_OFFSET_0 = 0x00,
  SET_COM_PINS_CONFIG_CONTROL = 0xDA,
  SET_COM_PINS_SEQ_NO_REMAP = 0x02,
  SET_COM_PINS_SEQ_REMAP = 0x22,
  SET_COM_PINS_ALT_NO_REMAP = 0x12,
  SET_COM_PINS_ALT_REMAP = 0x32,
  SET_CHARGE_BUMP_CONTROL = 0x8D,
  SET_CHARGE_BUMP_ON = 0x14,
  SET_CHARGE_BUMP_OFF = 0x10,

  SET_PRECHARGE_CONTROL = 0xD9,
  SET_PRECHARGE_PHASE1_1_PHASE2_15 = 0xF1,
  SET_VCOM_DESELECT_LEVEL_CONTROL = 0xDB,
  SET_VCOM_DESELECT_LEVEL_07VCC = 0x40
};

enum CONTROL_BYTE_COMMANDS {
  SEND_SINGLE_CMD = 0x80,
  SEND_SINGLE_DATA = 0xC0,
  SEND_MULTIPLE_CMDS = 0x00,
  SEND_MULTIPLE_DATA = 0x40,
};
#endif /* SSD_1306_ENUM_H */
